-- Create messages table
CREATE TABLE messages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT    NOT NULL,
  content    TEXT    NOT NULL CHECK (char_length(content) <= 280),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Public read"  ON messages FOR SELECT USING (true);
CREATE POLICY "Public write" ON messages FOR INSERT WITH CHECK (true); 